SET search_path TO bd053_schema, public; 

/*
CREATE TYPE estado_pagamento AS ENUM( 'pago','por pagar');
CREATE TYPE tipo_utilizador AS ENUM( 'docente','aluno');
*/

DROP TABLE IF EXISTS course CASCADE;
DROP TABLE IF EXISTS department CASCADE;
DROP TABLE IF EXISTS instructor CASCADE;
DROP TABLE IF EXISTS prereq CASCADE;
DROP TABLE IF EXISTS section CASCADE;
DROP TABLE IF EXISTS takes CASCADE;
DROP TABLE IF EXISTS test CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS firsttable CASCADE;

DROP TABLE IF EXISTS multa CASCADE; 
DROP TABLE IF EXISTS reserva CASCADE; 
DROP TABLE IF EXISTS emprestar CASCADE; 

DROP TABLE IF EXISTS livro CASCADE; 
CREATE TABLE livro ( 
 	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
 	titulo VARCHAR(250) NOT NULL,
 	genero VARCHAR(250) ,
 	n_paginas NUMERIC(4,0) DEFAULT 0,
 	descricao VARCHAR(750) DEFAULT 'não disponivel',
 	data_publicacao DATE ,
 	avaliacao NUMERIC(2,1) DEFAULT 0,
	n_avaliacoes INT DEFAULT 0,
 	lingua VARCHAR(15) DEFAULT 'Portugues',
	UNIQUE( titulo ),
	UNIQUE (titulo,id)
); 

DROP TABLE IF EXISTS fisico CASCADE; 
CREATE TABLE fisico ( 
	id_livro int PRIMARY KEY,
 	Copias_reservadas int DEFAULT 0,
 	Copias_emprestadas int DEFAULT 0,
 	Copias_totais int DEFAULT 1,
 	FOREIGN KEY (id_livro) REFERENCES livro(id),
	CHECK( Copias_totais > 0) 
); 

DROP TABLE IF EXISTS digital; 
CREATE TABLE digital ( 
	id int PRIMARY KEY,
 	n_acessos INTEGER ,
 	ficheiro_livro BYTEA , -- terei que mudar?
	FOREIGN KEY (id) REFERENCES livro(id)
); 

DROP TABLE IF EXISTS utilizador CASCADE; 
CREATE TABLE utilizador ( 
	id SERIAL PRIMARY KEY,
	email VARCHAR(50) NOT NULL UNIQUE,
  	nome VARCHAR(80) ,
 	categoria tipo_utilizador ,
 	faculdade VARCHAR(40) ,
 	password VARCHAR(15) NOT NULL,
 	n_telemovel NUMERIC(9,0),
	UNIQUE (email,nome),
	UNIQUE( id,email )
); 

DROP TABLE IF EXISTS aluno CASCADE; 
CREATE TABLE aluno( 
 	id INT PRIMARY KEY ,
 	Curso VARCHAR(25) ,
 	id_aluno VARCHAR(10),
	FOREIGN KEY (id) REFERENCES utilizador(id) ON DELETE CASCADE
) ;

DROP TABLE IF EXISTS periodico CASCADE; 
CREATE TABLE periodico( 
	id SERIAL PRIMARY KEY, 
 	nome VARCHAR(250) NOT NULL ,
 	periodicidade VARCHAR(15),
	UNIQUE (id,nome),
	UNIQUE (nome)
) ;

DROP TABLE IF EXISTS autor CASCADE; 
CREATE TABLE autor( 
	id SERIAL PRIMARY KEY ,
 	nome VARCHAR(80)
) ;

DROP TABLE IF EXISTS funcionario CASCADE; 
CREATE TABLE funcionario( 
 	id SERIAL PRIMARY KEY ,
 	password VARCHAR(15) NOT NULL 
) ;

DROP TABLE IF EXISTS biblioteca CASCADE; 
CREATE TABLE biblioteca( 
	id SERIAL PRIMARY KEY,
 	nome VARCHAR(35) UNIQUE NOT NULL,
 	faculdade VARCHAR(40) 
) ;

DROP TABLE IF EXISTS sala CASCADE; 
CREATE TABLE sala( 
 	id SERIAL PRIMARY KEY, 
 	capacidade NUMERIC(2,0) 
) ;

DROP TABLE IF EXISTS emprestimo CASCADE; 
CREATE TABLE emprestimo( 
	id SERIAL PRIMARY KEY,
 	data_emprestimo DATE, 
 	prazo_retorno DATE,
	ativo BOOLEAN DEFAULT TRUE,
	UNIQUE(id,data_emprestimo,prazo_retorno),
	CONSTRAINT prazo_retorno CHECK (prazo_retorno > data_emprestimo)
) ;

DROP TABLE IF EXISTS reserva CASCADE; 
CREATE TABLE reserva( 
	id SERIAL PRIMARY KEY,
 	data_reserva DATE, 
 	prazo_limite DATE,
	ativo BOOLEAN DEFAULT TRUE,
	UNIQUE(id,Data_reserva,prazo_limite),
	CONSTRAINT data_prazo CHECK (prazo_limite > data_reserva)
) ;

DROP TABLE IF EXISTS acesso CASCADE; 
CREATE TABLE acesso( 
	tempo_acesso TIMESTAMP,
	id_aluno INT,
	PRIMARY KEY(tempo_acesso,id_aluno),
	FOREIGN KEY (id_aluno) REFERENCES utilizador(id) ON DELETE CASCADE
) ;

DROP TABLE IF EXISTS agenda; 
CREATE TABLE agenda( 
	sala_id int,
 	data_reserva DATE,
 	hora_inicio NUMERIC(2,0) ,
 	hora_fim NUMERIC(2,0) , 
	PRIMARY KEY( sala_id, data_reserva, hora_inicio),
	FOREIGN KEY (sala_id) REFERENCES sala(id),
	CONSTRAINT horario CHECK (hora_inicio between 8 AND 17 and hora_fim between 9 AND 18),
	CONSTRAINT horas_salas CHECK (hora_fim - hora_inicio <= 3 AND hora_fim > hora_inicio)
	-- só podem ser reservadas por 3 horas
) ;

-- RELACOES: 

-- TODO entidade e referencia
DROP TABLE IF EXISTS multar CASCADE; 
CREATE TABLE multar( 
	id_aluno INT,
	emprestimo_id INT,
	data_emprestimo DATE,
 	prazo_limite DATE ,
 	estado estado_pagamento DEFAULT 'por pagar',
 	entidade INTEGER DEFAULT 99999,
 	referencia INTEGER DEFAULT 100000000,
 	valor FLOAT(3) DEFAULT 0.5,
	PRIMARY KEY (id_aluno, emprestimo_id) ,
	FOREIGN KEY (id_aluno) REFERENCES utilizador(id) ON DELETE CASCADE,
	FOREIGN KEY (emprestimo_id,prazo_limite,data_emprestimo) REFERENCES emprestimo(id,prazo_retorno,data_emprestimo) ON DELETE CASCADE
) ;

DROP TABLE IF EXISTS avaliar CASCADE; 
CREATE TABLE avaliar( 
	id_aluno INT,
	livro_id INT,
 	avaliacao NUMERIC(3,1) CONSTRAINT avaliacao_1_a_5 CHECK (avaliacao BETWEEN 1 and 5),
	PRIMARY KEY (id_aluno,livro_id) ,
	FOREIGN KEY (id_aluno) REFERENCES utilizador(id),
	FOREIGN KEY (livro_id) REFERENCES livro(id)
) ;


DROP TABLE IF EXISTS acessar; 

DROP TABLE IF EXISTS livro_acessado; 
CREATE TABLE livro_acessado( 
	id_aluno INT,
	id_livro INT,
	titulo_livro VARCHAR(250),
	tempo_acesso TIMESTAMP,
	PRIMARY KEY (id_aluno,id_livro, tempo_acesso),
	FOREIGN KEY (id_aluno) REFERENCES utilizador(id) ON DELETE CASCADE,
	FOREIGN KEY (id_livro) REFERENCES livro(id)
);

-- AQUI

DROP TABLE IF EXISTS reserva_livro; 
CREATE TABLE reserva_livro( 
	reserva_id INT,
	livro_id INT,
	titulo VARCHAR(250),
	Data_reserva DATE, 
 	prazo_limite DATE,
	PRIMARY KEY (reserva_id,livro_id),
	FOREIGN KEY (reserva_id,Data_reserva,prazo_limite) REFERENCES reserva(id,data_reserva,prazo_limite)  ON DELETE CASCADE,
	FOREIGN KEY (livro_id,titulo) REFERENCES livro(id,titulo)
) ;

DROP TABLE IF EXISTS reserva_local; 
CREATE TABLE reserva_local( 
	reserva_id INT,
	data_reserva DATE, 
 	prazo_limite DATE,
	biblioteca_id INT,
	PRIMARY KEY (reserva_id,biblioteca_id),
	FOREIGN KEY (reserva_id,data_reserva,prazo_limite) REFERENCES reserva(id,data_reserva,prazo_limite)  ON DELETE CASCADE,
	FOREIGN KEY (biblioteca_id) REFERENCES biblioteca(id)
) ;

DROP TABLE IF EXISTS reserva_utilizador; 
CREATE TABLE reserva_utilizador( 
	id_aluno INT,
	reserva_id INT,
	data_reserva DATE, 
 	prazo_limite DATE,
	PRIMARY KEY (reserva_id,id_aluno),
	FOREIGN KEY (reserva_id,Data_reserva,prazo_limite) REFERENCES reserva(id,data_reserva,prazo_limite)  ON DELETE CASCADE,
	FOREIGN KEY (id_aluno) REFERENCES utilizador(id) ON DELETE CASCADE
) ;

DROP TABLE IF EXISTS emprestar_utilizador; 
CREATE TABLE emprestar_utilizador( 
	id_aluno INT,
	emprestimo_id int,
	data_emprestimo DATE, 
 	prazo_retorno DATE,
	PRIMARY KEY (emprestimo_id,id_aluno),
	FOREIGN KEY (emprestimo_id,data_emprestimo,prazo_retorno) REFERENCES emprestimo(id,data_emprestimo,prazo_retorno)  ON DELETE CASCADE,
	FOREIGN KEY (id_aluno) REFERENCES utilizador(id) ON DELETE CASCADE
) ;

DROP TABLE IF EXISTS emprestar_local; 
CREATE TABLE emprestar_local( 
	emprestimo_id int,
	biblioteca_id int,
	data_emprestimo DATE, 
 	prazo_retorno DATE,
	PRIMARY KEY (emprestimo_id,biblioteca_id),
	FOREIGN KEY (emprestimo_id,data_emprestimo,prazo_retorno) REFERENCES emprestimo(id,data_emprestimo,prazo_retorno)  ON DELETE CASCADE,
	FOREIGN KEY (biblioteca_id) REFERENCES biblioteca(id)
) ;

DROP TABLE IF EXISTS emprestar_livro; 
CREATE TABLE emprestar_livro( 
	emprestimo_id int,
	livro_id int,
	data_emprestimo DATE, 
 	prazo_retorno DATE,
	PRIMARY KEY (emprestimo_id,livro_id),
	FOREIGN KEY (emprestimo_id,data_emprestimo,prazo_retorno) REFERENCES emprestimo(id,data_emprestimo,prazo_retorno)  ON DELETE CASCADE,
	FOREIGN KEY (livro_id) REFERENCES livro(id)
) ;

DROP TABLE IF EXISTS emprestar; 


DROP TABLE IF EXISTS agendar; 
CREATE TABLE agendar( 
	id_aluno INT,
	sala_id INT,
 	Data_reserva DATE,
 	hora_inicio NUMERIC(2,0) ,
 	hora_fim NUMERIC(2,0) , 
	PRIMARY KEY(id_aluno,sala_id,data_reserva,hora_inicio),
	FOREIGN KEY (id_aluno) REFERENCES utilizador(id) ON DELETE CASCADE,
	FOREIGN KEY (sala_id) REFERENCES sala(id)
	-- só podem ser reservadas por 3 horas
) ;

 
DROP TABLE IF EXISTS local_livro; 
CREATE TABLE local_livro( 
	livro_id SERIAL, 
 	biblioteca_id INT, 
 	n_disp INT DEFAULT 1,
	n_reservadas INT DEFAULT 0,
	n_emprestadas INT DEFAULT 0,
 	total_copias INT DEFAULT 1,
	PRIMARY KEY (livro_id,biblioteca_id),
	FOREIGN KEY (livro_id) REFERENCES livro(ID),
	FOREIGN KEY (biblioteca_id) REFERENCES biblioteca(id),
	CONSTRAINT n_copia_disp_min CHECK( n_disp >= 0 ),
	CONSTRAINT coerencia_total CHECK( total_copias = n_disp + n_emprestadas + n_reservadas)
 ) ;

 
DROP TABLE IF EXISTS local_sala; 
CREATE TABLE local_sala( 
 	biblioteca_id INT, 
 	sala_id INT,
	PRIMARY KEY (biblioteca_id,sala_id),
	FOREIGN KEY (biblioteca_id) REFERENCES biblioteca(id),
	FOREIGN KEY (sala_id) REFERENCES sala(id)
) ;

DROP TABLE IF EXISTS local_trabalho; 
CREATE TABLE local_trabalho( 
 	biblioteca_id INT, 
 	funcionario_id INT ,
	PRIMARY KEY (biblioteca_id,funcionario_id),
	FOREIGN KEY (biblioteca_id) REFERENCES biblioteca(id),
	FOREIGN KEY (funcionario_id) REFERENCES funcionario(id)
) ;

 
DROP TABLE IF EXISTS autoria; 
CREATE TABLE autoria( 
	livro_id SERIAL,
	autor_id SERIAL,
	PRIMARY KEY (livro_id,autor_id),
	FOREIGN KEY (livro_id) REFERENCES livro(id),
	FOREIGN KEY (autor_id) REFERENCES autor(id)
) ;

DROP TABLE IF EXISTS periodicidade; 
CREATE TABLE periodicidade(
	livro_id serial,
	periodico_id serial,
	PRIMARY KEY (periodico_id, livro_id) ,
	FOREIGN KEY (periodico_id) REFERENCES periodico(id), 
	FOREIGN KEY (livro_id) REFERENCES livro(id) 
);

DROP TABLE IF EXISTS acessar; 

